addons:
  sonarcloud:
    organization: "elenemendi"
    token: "2a8aef9513ce8646122ae1247875cfb962826868"
script:
#the following comman line builds the project, runs te thests with coverage
#and then execute te sonarcloud analysis
- mvn clean org.jacoco:jacoco-maven-plugin:pregare-agent org.jacoco:jacoco-maven-plugin:report install sonar:sonar
